version: "3"
services:
  install:
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
  build: 
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"  
  serve:
    image: node:18
    ports:
      - "8099:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build && npm run serve"          
  dev:
    #docker-compose run --rm dev bash
    user: node
    image: node:18
    working_dir: /data
    volumes:
      - .:/data
    tty: true
    stdin_open: true